export enum OperationType {
  FUEL = "fuel",
  ODOMETER = "odometer",
  SERVICE = "service",
  TRANSACTION = "transaction",
  EXPENSE = "expense",
  INCOME = "income",
  VEHICLE_LIFECYCLE = "vehicle_lifecycle",
  DRIVER_ASSIGNMENT = "driver_assignment",
  REMINDER = "reminder",
  CHECKLIST = "checklist",
  ROUTE = "route",
}

export enum OperationSortField {
  CREATED_AT = "createdAt",
  UPDATED_AT = "updatedAt",
}

export enum SystemCategory {
  REGISTRATION = "Registration",
  DECOMMISSION = "Decommission",
  SALE = "Sale",
  TRANSFER = "Transfer",
  ASSIGN = "Assign",
  UNASSIGN = "Unassign",
  CANCEL = "Cancel",
  GASOLINE = "Gasoline",
  DIESEL = "Diesel",
  ELECTRIC_CHARGE = "Electric charge",
  HYBRID = "Hybrid",
  OIL_CHANGE = "Oil change",
  BRAKE_CHECK = "Brake check",
  TIRE_CHANGE = "Tire change",
  FILTER_CHANGE = "Filter change",
  AIR_CONDITIONING_CLEANING = "Air conditioning cleaning",
  GENERAL_MAINTENANCE = "General maintenance",
  INSURANCE = "Insurance",
  TOLL = "Toll",
  PARKING = "Parking",
  RENTAL = "Rental",
  TAX = "Tax",
  FINE = "Fine",
  RENTAL_INCOME = "Rental income",
  DELIVERY_FEE = "Delivery fee",
  COMPENSATION = "Compensation",
  INSURANCE_RENEWAL = "Insurance renewal",
  LICENSE_CHECK = "License check",
  SERVICE_DUE = "Service due",
  INSPECTION_DUE = "Inspection due",
  PRE_TRIP = "Pre trip",
  POST_TRIP = "Post trip",
  SAFETY_CHECK = "Safety check",
  DELIVERY_ROUTE = "Delivery route",
  PICKUP_ROUTE = "Pickup route",
  ROUND_TRIP = "Round trip",
}

export const OperationCategories: Record<OperationType, SystemCategory[]> = {
  [OperationType.FUEL]: [
    SystemCategory.GASOLINE,
    SystemCategory.DIESEL,
    SystemCategory.ELECTRIC_CHARGE,
    SystemCategory.HYBRID,
  ],
  [OperationType.VEHICLE_LIFECYCLE]: [
    SystemCategory.REGISTRATION,
    SystemCategory.DECOMMISSION,
    SystemCategory.SALE,
    SystemCategory.TRANSFER,
  ],
  [OperationType.DRIVER_ASSIGNMENT]: [
    SystemCategory.ASSIGN,
    SystemCategory.UNASSIGN,
    SystemCategory.CANCEL,
  ],
  [OperationType.SERVICE]: [
    SystemCategory.OIL_CHANGE,
    SystemCategory.BRAKE_CHECK,
    SystemCategory.TIRE_CHANGE,
    SystemCategory.FILTER_CHANGE,
    SystemCategory.AIR_CONDITIONING_CLEANING,
    SystemCategory.GENERAL_MAINTENANCE,
  ],
  [OperationType.EXPENSE]: [
    SystemCategory.INSURANCE,
    SystemCategory.TOLL,
    SystemCategory.PARKING,
    SystemCategory.RENTAL,
    SystemCategory.TAX,
    SystemCategory.FINE,
  ],
  [OperationType.INCOME]: [
    SystemCategory.RENTAL_INCOME,
    SystemCategory.DELIVERY_FEE,
    SystemCategory.COMPENSATION,
  ],
  [OperationType.REMINDER]: [
    SystemCategory.INSURANCE_RENEWAL,
    SystemCategory.LICENSE_CHECK,
    SystemCategory.SERVICE_DUE,
    SystemCategory.INSPECTION_DUE,
  ],
  [OperationType.CHECKLIST]: [
    SystemCategory.PRE_TRIP,
    SystemCategory.POST_TRIP,
    SystemCategory.SAFETY_CHECK,
  ],
  [OperationType.ROUTE]: [
    SystemCategory.DELIVERY_ROUTE,
    SystemCategory.PICKUP_ROUTE,
    SystemCategory.ROUND_TRIP,
  ],
  [OperationType.ODOMETER]: [],
  [OperationType.TRANSACTION]: [],
};
