/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthForYouRouteRouteImport } from './routes/_auth/for-you/route'
import { Route as AuthTenantsIndexRouteImport } from './routes/_auth/tenants/index'
import { Route as AuthInvitationsIndexRouteImport } from './routes/_auth/invitations/index'
import { Route as AuthTenantsTenantIdIndexRouteImport } from './routes/_auth/tenants/$tenantId/index'
import { Route as AuthTenantsTenantIdVehiclesIndexRouteImport } from './routes/_auth/tenants/$tenantId/vehicles/index'
import { Route as AuthTenantsTenantIdTransactionIndexRouteImport } from './routes/_auth/tenants/$tenantId/transaction/index'
import { Route as AuthTenantsTenantIdServiceIndexRouteImport } from './routes/_auth/tenants/$tenantId/service/index'
import { Route as AuthTenantsTenantIdOperationIndexRouteImport } from './routes/_auth/tenants/$tenantId/operation/index'
import { Route as AuthTenantsTenantIdOdometerIndexRouteImport } from './routes/_auth/tenants/$tenantId/odometer/index'
import { Route as AuthTenantsTenantIdMembersIndexRouteImport } from './routes/_auth/tenants/$tenantId/members/index'
import { Route as AuthTenantsTenantIdFuelIndexRouteImport } from './routes/_auth/tenants/$tenantId/fuel/index'
import { Route as AuthTenantsTenantIdVehiclesCreateRouteImport } from './routes/_auth/tenants/$tenantId/vehicles/create'
import { Route as AuthTenantsTenantIdTransactionCreateRouteImport } from './routes/_auth/tenants/$tenantId/transaction/create'
import { Route as AuthTenantsTenantIdTransactionTransactionIdRouteImport } from './routes/_auth/tenants/$tenantId/transaction/$transactionId'
import { Route as AuthTenantsTenantIdServiceCreateRouteImport } from './routes/_auth/tenants/$tenantId/service/create'
import { Route as AuthTenantsTenantIdServiceServiceIdRouteImport } from './routes/_auth/tenants/$tenantId/service/$serviceId'
import { Route as AuthTenantsTenantIdOdometerCreateRouteImport } from './routes/_auth/tenants/$tenantId/odometer/create'
import { Route as AuthTenantsTenantIdOdometerOdometerIdRouteImport } from './routes/_auth/tenants/$tenantId/odometer/$odometerId'
import { Route as AuthTenantsTenantIdFuelCreateRouteImport } from './routes/_auth/tenants/$tenantId/fuel/create'
import { Route as AuthTenantsTenantIdFuelFuelIdRouteImport } from './routes/_auth/tenants/$tenantId/fuel/$fuelId'
import { Route as AuthTenantsTenantIdVehiclesVehicleIdIndexRouteImport } from './routes/_auth/tenants/$tenantId/vehicles/$vehicleId/index'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthForYouRouteRoute = AuthForYouRouteRouteImport.update({
  id: '/for-you',
  path: '/for-you',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTenantsIndexRoute = AuthTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthInvitationsIndexRoute = AuthInvitationsIndexRouteImport.update({
  id: '/invitations/',
  path: '/invitations/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthTenantsTenantIdIndexRoute =
  AuthTenantsTenantIdIndexRouteImport.update({
    id: '/tenants/$tenantId/',
    path: '/tenants/$tenantId/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdVehiclesIndexRoute =
  AuthTenantsTenantIdVehiclesIndexRouteImport.update({
    id: '/tenants/$tenantId/vehicles/',
    path: '/tenants/$tenantId/vehicles/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdTransactionIndexRoute =
  AuthTenantsTenantIdTransactionIndexRouteImport.update({
    id: '/tenants/$tenantId/transaction/',
    path: '/tenants/$tenantId/transaction/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdServiceIndexRoute =
  AuthTenantsTenantIdServiceIndexRouteImport.update({
    id: '/tenants/$tenantId/service/',
    path: '/tenants/$tenantId/service/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdOperationIndexRoute =
  AuthTenantsTenantIdOperationIndexRouteImport.update({
    id: '/tenants/$tenantId/operation/',
    path: '/tenants/$tenantId/operation/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdOdometerIndexRoute =
  AuthTenantsTenantIdOdometerIndexRouteImport.update({
    id: '/tenants/$tenantId/odometer/',
    path: '/tenants/$tenantId/odometer/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdMembersIndexRoute =
  AuthTenantsTenantIdMembersIndexRouteImport.update({
    id: '/tenants/$tenantId/members/',
    path: '/tenants/$tenantId/members/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdFuelIndexRoute =
  AuthTenantsTenantIdFuelIndexRouteImport.update({
    id: '/tenants/$tenantId/fuel/',
    path: '/tenants/$tenantId/fuel/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdVehiclesCreateRoute =
  AuthTenantsTenantIdVehiclesCreateRouteImport.update({
    id: '/tenants/$tenantId/vehicles/create',
    path: '/tenants/$tenantId/vehicles/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdTransactionCreateRoute =
  AuthTenantsTenantIdTransactionCreateRouteImport.update({
    id: '/tenants/$tenantId/transaction/create',
    path: '/tenants/$tenantId/transaction/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdTransactionTransactionIdRoute =
  AuthTenantsTenantIdTransactionTransactionIdRouteImport.update({
    id: '/tenants/$tenantId/transaction/$transactionId',
    path: '/tenants/$tenantId/transaction/$transactionId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdServiceCreateRoute =
  AuthTenantsTenantIdServiceCreateRouteImport.update({
    id: '/tenants/$tenantId/service/create',
    path: '/tenants/$tenantId/service/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdServiceServiceIdRoute =
  AuthTenantsTenantIdServiceServiceIdRouteImport.update({
    id: '/tenants/$tenantId/service/$serviceId',
    path: '/tenants/$tenantId/service/$serviceId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdOdometerCreateRoute =
  AuthTenantsTenantIdOdometerCreateRouteImport.update({
    id: '/tenants/$tenantId/odometer/create',
    path: '/tenants/$tenantId/odometer/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdOdometerOdometerIdRoute =
  AuthTenantsTenantIdOdometerOdometerIdRouteImport.update({
    id: '/tenants/$tenantId/odometer/$odometerId',
    path: '/tenants/$tenantId/odometer/$odometerId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdFuelCreateRoute =
  AuthTenantsTenantIdFuelCreateRouteImport.update({
    id: '/tenants/$tenantId/fuel/create',
    path: '/tenants/$tenantId/fuel/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdFuelFuelIdRoute =
  AuthTenantsTenantIdFuelFuelIdRouteImport.update({
    id: '/tenants/$tenantId/fuel/$fuelId',
    path: '/tenants/$tenantId/fuel/$fuelId',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthTenantsTenantIdVehiclesVehicleIdIndexRoute =
  AuthTenantsTenantIdVehiclesVehicleIdIndexRouteImport.update({
    id: '/tenants/$tenantId/vehicles/$vehicleId/',
    path: '/tenants/$tenantId/vehicles/$vehicleId/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-you': typeof AuthForYouRouteRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/invitations': typeof AuthInvitationsIndexRoute
  '/tenants': typeof AuthTenantsIndexRoute
  '/tenants/$tenantId': typeof AuthTenantsTenantIdIndexRoute
  '/tenants/$tenantId/fuel/$fuelId': typeof AuthTenantsTenantIdFuelFuelIdRoute
  '/tenants/$tenantId/fuel/create': typeof AuthTenantsTenantIdFuelCreateRoute
  '/tenants/$tenantId/odometer/$odometerId': typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  '/tenants/$tenantId/odometer/create': typeof AuthTenantsTenantIdOdometerCreateRoute
  '/tenants/$tenantId/service/$serviceId': typeof AuthTenantsTenantIdServiceServiceIdRoute
  '/tenants/$tenantId/service/create': typeof AuthTenantsTenantIdServiceCreateRoute
  '/tenants/$tenantId/transaction/$transactionId': typeof AuthTenantsTenantIdTransactionTransactionIdRoute
  '/tenants/$tenantId/transaction/create': typeof AuthTenantsTenantIdTransactionCreateRoute
  '/tenants/$tenantId/vehicles/create': typeof AuthTenantsTenantIdVehiclesCreateRoute
  '/tenants/$tenantId/fuel': typeof AuthTenantsTenantIdFuelIndexRoute
  '/tenants/$tenantId/members': typeof AuthTenantsTenantIdMembersIndexRoute
  '/tenants/$tenantId/odometer': typeof AuthTenantsTenantIdOdometerIndexRoute
  '/tenants/$tenantId/operation': typeof AuthTenantsTenantIdOperationIndexRoute
  '/tenants/$tenantId/service': typeof AuthTenantsTenantIdServiceIndexRoute
  '/tenants/$tenantId/transaction': typeof AuthTenantsTenantIdTransactionIndexRoute
  '/tenants/$tenantId/vehicles': typeof AuthTenantsTenantIdVehiclesIndexRoute
  '/tenants/$tenantId/vehicles/$vehicleId': typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-you': typeof AuthForYouRouteRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/invitations': typeof AuthInvitationsIndexRoute
  '/tenants': typeof AuthTenantsIndexRoute
  '/tenants/$tenantId': typeof AuthTenantsTenantIdIndexRoute
  '/tenants/$tenantId/fuel/$fuelId': typeof AuthTenantsTenantIdFuelFuelIdRoute
  '/tenants/$tenantId/fuel/create': typeof AuthTenantsTenantIdFuelCreateRoute
  '/tenants/$tenantId/odometer/$odometerId': typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  '/tenants/$tenantId/odometer/create': typeof AuthTenantsTenantIdOdometerCreateRoute
  '/tenants/$tenantId/service/$serviceId': typeof AuthTenantsTenantIdServiceServiceIdRoute
  '/tenants/$tenantId/service/create': typeof AuthTenantsTenantIdServiceCreateRoute
  '/tenants/$tenantId/transaction/$transactionId': typeof AuthTenantsTenantIdTransactionTransactionIdRoute
  '/tenants/$tenantId/transaction/create': typeof AuthTenantsTenantIdTransactionCreateRoute
  '/tenants/$tenantId/vehicles/create': typeof AuthTenantsTenantIdVehiclesCreateRoute
  '/tenants/$tenantId/fuel': typeof AuthTenantsTenantIdFuelIndexRoute
  '/tenants/$tenantId/members': typeof AuthTenantsTenantIdMembersIndexRoute
  '/tenants/$tenantId/odometer': typeof AuthTenantsTenantIdOdometerIndexRoute
  '/tenants/$tenantId/operation': typeof AuthTenantsTenantIdOperationIndexRoute
  '/tenants/$tenantId/service': typeof AuthTenantsTenantIdServiceIndexRoute
  '/tenants/$tenantId/transaction': typeof AuthTenantsTenantIdTransactionIndexRoute
  '/tenants/$tenantId/vehicles': typeof AuthTenantsTenantIdVehiclesIndexRoute
  '/tenants/$tenantId/vehicles/$vehicleId': typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/for-you': typeof AuthForYouRouteRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_auth/invitations/': typeof AuthInvitationsIndexRoute
  '/_auth/tenants/': typeof AuthTenantsIndexRoute
  '/_auth/tenants/$tenantId/': typeof AuthTenantsTenantIdIndexRoute
  '/_auth/tenants/$tenantId/fuel/$fuelId': typeof AuthTenantsTenantIdFuelFuelIdRoute
  '/_auth/tenants/$tenantId/fuel/create': typeof AuthTenantsTenantIdFuelCreateRoute
  '/_auth/tenants/$tenantId/odometer/$odometerId': typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  '/_auth/tenants/$tenantId/odometer/create': typeof AuthTenantsTenantIdOdometerCreateRoute
  '/_auth/tenants/$tenantId/service/$serviceId': typeof AuthTenantsTenantIdServiceServiceIdRoute
  '/_auth/tenants/$tenantId/service/create': typeof AuthTenantsTenantIdServiceCreateRoute
  '/_auth/tenants/$tenantId/transaction/$transactionId': typeof AuthTenantsTenantIdTransactionTransactionIdRoute
  '/_auth/tenants/$tenantId/transaction/create': typeof AuthTenantsTenantIdTransactionCreateRoute
  '/_auth/tenants/$tenantId/vehicles/create': typeof AuthTenantsTenantIdVehiclesCreateRoute
  '/_auth/tenants/$tenantId/fuel/': typeof AuthTenantsTenantIdFuelIndexRoute
  '/_auth/tenants/$tenantId/members/': typeof AuthTenantsTenantIdMembersIndexRoute
  '/_auth/tenants/$tenantId/odometer/': typeof AuthTenantsTenantIdOdometerIndexRoute
  '/_auth/tenants/$tenantId/operation/': typeof AuthTenantsTenantIdOperationIndexRoute
  '/_auth/tenants/$tenantId/service/': typeof AuthTenantsTenantIdServiceIndexRoute
  '/_auth/tenants/$tenantId/transaction/': typeof AuthTenantsTenantIdTransactionIndexRoute
  '/_auth/tenants/$tenantId/vehicles/': typeof AuthTenantsTenantIdVehiclesIndexRoute
  '/_auth/tenants/$tenantId/vehicles/$vehicleId/': typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/for-you'
    | '/login'
    | '/register'
    | '/invitations'
    | '/tenants'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/fuel/$fuelId'
    | '/tenants/$tenantId/fuel/create'
    | '/tenants/$tenantId/odometer/$odometerId'
    | '/tenants/$tenantId/odometer/create'
    | '/tenants/$tenantId/service/$serviceId'
    | '/tenants/$tenantId/service/create'
    | '/tenants/$tenantId/transaction/$transactionId'
    | '/tenants/$tenantId/transaction/create'
    | '/tenants/$tenantId/vehicles/create'
    | '/tenants/$tenantId/fuel'
    | '/tenants/$tenantId/members'
    | '/tenants/$tenantId/odometer'
    | '/tenants/$tenantId/operation'
    | '/tenants/$tenantId/service'
    | '/tenants/$tenantId/transaction'
    | '/tenants/$tenantId/vehicles'
    | '/tenants/$tenantId/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/for-you'
    | '/login'
    | '/register'
    | '/invitations'
    | '/tenants'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/fuel/$fuelId'
    | '/tenants/$tenantId/fuel/create'
    | '/tenants/$tenantId/odometer/$odometerId'
    | '/tenants/$tenantId/odometer/create'
    | '/tenants/$tenantId/service/$serviceId'
    | '/tenants/$tenantId/service/create'
    | '/tenants/$tenantId/transaction/$transactionId'
    | '/tenants/$tenantId/transaction/create'
    | '/tenants/$tenantId/vehicles/create'
    | '/tenants/$tenantId/fuel'
    | '/tenants/$tenantId/members'
    | '/tenants/$tenantId/odometer'
    | '/tenants/$tenantId/operation'
    | '/tenants/$tenantId/service'
    | '/tenants/$tenantId/transaction'
    | '/tenants/$tenantId/vehicles'
    | '/tenants/$tenantId/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/for-you'
    | '/_guest/login'
    | '/_guest/register'
    | '/_auth/invitations/'
    | '/_auth/tenants/'
    | '/_auth/tenants/$tenantId/'
    | '/_auth/tenants/$tenantId/fuel/$fuelId'
    | '/_auth/tenants/$tenantId/fuel/create'
    | '/_auth/tenants/$tenantId/odometer/$odometerId'
    | '/_auth/tenants/$tenantId/odometer/create'
    | '/_auth/tenants/$tenantId/service/$serviceId'
    | '/_auth/tenants/$tenantId/service/create'
    | '/_auth/tenants/$tenantId/transaction/$transactionId'
    | '/_auth/tenants/$tenantId/transaction/create'
    | '/_auth/tenants/$tenantId/vehicles/create'
    | '/_auth/tenants/$tenantId/fuel/'
    | '/_auth/tenants/$tenantId/members/'
    | '/_auth/tenants/$tenantId/odometer/'
    | '/_auth/tenants/$tenantId/operation/'
    | '/_auth/tenants/$tenantId/service/'
    | '/_auth/tenants/$tenantId/transaction/'
    | '/_auth/tenants/$tenantId/vehicles/'
    | '/_auth/tenants/$tenantId/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/for-you': {
      id: '/_auth/for-you'
      path: '/for-you'
      fullPath: '/for-you'
      preLoaderRoute: typeof AuthForYouRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/': {
      id: '/_auth/tenants/'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthTenantsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/invitations/': {
      id: '/_auth/invitations/'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthInvitationsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/': {
      id: '/_auth/tenants/$tenantId/'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthTenantsTenantIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/vehicles/': {
      id: '/_auth/tenants/$tenantId/vehicles/'
      path: '/tenants/$tenantId/vehicles'
      fullPath: '/tenants/$tenantId/vehicles'
      preLoaderRoute: typeof AuthTenantsTenantIdVehiclesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/transaction/': {
      id: '/_auth/tenants/$tenantId/transaction/'
      path: '/tenants/$tenantId/transaction'
      fullPath: '/tenants/$tenantId/transaction'
      preLoaderRoute: typeof AuthTenantsTenantIdTransactionIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/service/': {
      id: '/_auth/tenants/$tenantId/service/'
      path: '/tenants/$tenantId/service'
      fullPath: '/tenants/$tenantId/service'
      preLoaderRoute: typeof AuthTenantsTenantIdServiceIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/operation/': {
      id: '/_auth/tenants/$tenantId/operation/'
      path: '/tenants/$tenantId/operation'
      fullPath: '/tenants/$tenantId/operation'
      preLoaderRoute: typeof AuthTenantsTenantIdOperationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/odometer/': {
      id: '/_auth/tenants/$tenantId/odometer/'
      path: '/tenants/$tenantId/odometer'
      fullPath: '/tenants/$tenantId/odometer'
      preLoaderRoute: typeof AuthTenantsTenantIdOdometerIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/members/': {
      id: '/_auth/tenants/$tenantId/members/'
      path: '/tenants/$tenantId/members'
      fullPath: '/tenants/$tenantId/members'
      preLoaderRoute: typeof AuthTenantsTenantIdMembersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/fuel/': {
      id: '/_auth/tenants/$tenantId/fuel/'
      path: '/tenants/$tenantId/fuel'
      fullPath: '/tenants/$tenantId/fuel'
      preLoaderRoute: typeof AuthTenantsTenantIdFuelIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/vehicles/create': {
      id: '/_auth/tenants/$tenantId/vehicles/create'
      path: '/tenants/$tenantId/vehicles/create'
      fullPath: '/tenants/$tenantId/vehicles/create'
      preLoaderRoute: typeof AuthTenantsTenantIdVehiclesCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/transaction/create': {
      id: '/_auth/tenants/$tenantId/transaction/create'
      path: '/tenants/$tenantId/transaction/create'
      fullPath: '/tenants/$tenantId/transaction/create'
      preLoaderRoute: typeof AuthTenantsTenantIdTransactionCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/transaction/$transactionId': {
      id: '/_auth/tenants/$tenantId/transaction/$transactionId'
      path: '/tenants/$tenantId/transaction/$transactionId'
      fullPath: '/tenants/$tenantId/transaction/$transactionId'
      preLoaderRoute: typeof AuthTenantsTenantIdTransactionTransactionIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/service/create': {
      id: '/_auth/tenants/$tenantId/service/create'
      path: '/tenants/$tenantId/service/create'
      fullPath: '/tenants/$tenantId/service/create'
      preLoaderRoute: typeof AuthTenantsTenantIdServiceCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/service/$serviceId': {
      id: '/_auth/tenants/$tenantId/service/$serviceId'
      path: '/tenants/$tenantId/service/$serviceId'
      fullPath: '/tenants/$tenantId/service/$serviceId'
      preLoaderRoute: typeof AuthTenantsTenantIdServiceServiceIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/odometer/create': {
      id: '/_auth/tenants/$tenantId/odometer/create'
      path: '/tenants/$tenantId/odometer/create'
      fullPath: '/tenants/$tenantId/odometer/create'
      preLoaderRoute: typeof AuthTenantsTenantIdOdometerCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/odometer/$odometerId': {
      id: '/_auth/tenants/$tenantId/odometer/$odometerId'
      path: '/tenants/$tenantId/odometer/$odometerId'
      fullPath: '/tenants/$tenantId/odometer/$odometerId'
      preLoaderRoute: typeof AuthTenantsTenantIdOdometerOdometerIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/fuel/create': {
      id: '/_auth/tenants/$tenantId/fuel/create'
      path: '/tenants/$tenantId/fuel/create'
      fullPath: '/tenants/$tenantId/fuel/create'
      preLoaderRoute: typeof AuthTenantsTenantIdFuelCreateRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/fuel/$fuelId': {
      id: '/_auth/tenants/$tenantId/fuel/$fuelId'
      path: '/tenants/$tenantId/fuel/$fuelId'
      fullPath: '/tenants/$tenantId/fuel/$fuelId'
      preLoaderRoute: typeof AuthTenantsTenantIdFuelFuelIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/tenants/$tenantId/vehicles/$vehicleId/': {
      id: '/_auth/tenants/$tenantId/vehicles/$vehicleId/'
      path: '/tenants/$tenantId/vehicles/$vehicleId'
      fullPath: '/tenants/$tenantId/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForYouRouteRoute: typeof AuthForYouRouteRoute
  AuthInvitationsIndexRoute: typeof AuthInvitationsIndexRoute
  AuthTenantsIndexRoute: typeof AuthTenantsIndexRoute
  AuthTenantsTenantIdIndexRoute: typeof AuthTenantsTenantIdIndexRoute
  AuthTenantsTenantIdFuelFuelIdRoute: typeof AuthTenantsTenantIdFuelFuelIdRoute
  AuthTenantsTenantIdFuelCreateRoute: typeof AuthTenantsTenantIdFuelCreateRoute
  AuthTenantsTenantIdOdometerOdometerIdRoute: typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  AuthTenantsTenantIdOdometerCreateRoute: typeof AuthTenantsTenantIdOdometerCreateRoute
  AuthTenantsTenantIdServiceServiceIdRoute: typeof AuthTenantsTenantIdServiceServiceIdRoute
  AuthTenantsTenantIdServiceCreateRoute: typeof AuthTenantsTenantIdServiceCreateRoute
  AuthTenantsTenantIdTransactionTransactionIdRoute: typeof AuthTenantsTenantIdTransactionTransactionIdRoute
  AuthTenantsTenantIdTransactionCreateRoute: typeof AuthTenantsTenantIdTransactionCreateRoute
  AuthTenantsTenantIdVehiclesCreateRoute: typeof AuthTenantsTenantIdVehiclesCreateRoute
  AuthTenantsTenantIdFuelIndexRoute: typeof AuthTenantsTenantIdFuelIndexRoute
  AuthTenantsTenantIdMembersIndexRoute: typeof AuthTenantsTenantIdMembersIndexRoute
  AuthTenantsTenantIdOdometerIndexRoute: typeof AuthTenantsTenantIdOdometerIndexRoute
  AuthTenantsTenantIdOperationIndexRoute: typeof AuthTenantsTenantIdOperationIndexRoute
  AuthTenantsTenantIdServiceIndexRoute: typeof AuthTenantsTenantIdServiceIndexRoute
  AuthTenantsTenantIdTransactionIndexRoute: typeof AuthTenantsTenantIdTransactionIndexRoute
  AuthTenantsTenantIdVehiclesIndexRoute: typeof AuthTenantsTenantIdVehiclesIndexRoute
  AuthTenantsTenantIdVehiclesVehicleIdIndexRoute: typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForYouRouteRoute: AuthForYouRouteRoute,
  AuthInvitationsIndexRoute: AuthInvitationsIndexRoute,
  AuthTenantsIndexRoute: AuthTenantsIndexRoute,
  AuthTenantsTenantIdIndexRoute: AuthTenantsTenantIdIndexRoute,
  AuthTenantsTenantIdFuelFuelIdRoute: AuthTenantsTenantIdFuelFuelIdRoute,
  AuthTenantsTenantIdFuelCreateRoute: AuthTenantsTenantIdFuelCreateRoute,
  AuthTenantsTenantIdOdometerOdometerIdRoute:
    AuthTenantsTenantIdOdometerOdometerIdRoute,
  AuthTenantsTenantIdOdometerCreateRoute:
    AuthTenantsTenantIdOdometerCreateRoute,
  AuthTenantsTenantIdServiceServiceIdRoute:
    AuthTenantsTenantIdServiceServiceIdRoute,
  AuthTenantsTenantIdServiceCreateRoute: AuthTenantsTenantIdServiceCreateRoute,
  AuthTenantsTenantIdTransactionTransactionIdRoute:
    AuthTenantsTenantIdTransactionTransactionIdRoute,
  AuthTenantsTenantIdTransactionCreateRoute:
    AuthTenantsTenantIdTransactionCreateRoute,
  AuthTenantsTenantIdVehiclesCreateRoute:
    AuthTenantsTenantIdVehiclesCreateRoute,
  AuthTenantsTenantIdFuelIndexRoute: AuthTenantsTenantIdFuelIndexRoute,
  AuthTenantsTenantIdMembersIndexRoute: AuthTenantsTenantIdMembersIndexRoute,
  AuthTenantsTenantIdOdometerIndexRoute: AuthTenantsTenantIdOdometerIndexRoute,
  AuthTenantsTenantIdOperationIndexRoute:
    AuthTenantsTenantIdOperationIndexRoute,
  AuthTenantsTenantIdServiceIndexRoute: AuthTenantsTenantIdServiceIndexRoute,
  AuthTenantsTenantIdTransactionIndexRoute:
    AuthTenantsTenantIdTransactionIndexRoute,
  AuthTenantsTenantIdVehiclesIndexRoute: AuthTenantsTenantIdVehiclesIndexRoute,
  AuthTenantsTenantIdVehiclesVehicleIdIndexRoute:
    AuthTenantsTenantIdVehiclesVehicleIdIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
