/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthTenantsIndexRouteImport } from './routes/_auth/tenants/index'
import { Route as AuthOnboardingMultipleTenantsRouteImport } from './routes/_auth/onboarding/multiple-tenants'
import { Route as AuthOnboardingInvitationRouteImport } from './routes/_auth/onboarding/invitation'
import { Route as AuthOnboardingCreateTenantRouteImport } from './routes/_auth/onboarding/create-tenant'
import { Route as AuthTenantsTenantIdIndexRouteImport } from './routes/_auth/tenants/$tenantId/index'
import { Route as AuthTenantsTenantIdVehiclesIndexRouteImport } from './routes/_auth/tenants/$tenantId/vehicles/index'
import { Route as AuthTenantsTenantIdOperationIndexRouteImport } from './routes/_auth/tenants/$tenantId/operation/index'
import { Route as AuthTenantsTenantIdOdometerIndexRouteImport } from './routes/_auth/tenants/$tenantId/odometer/index'
import { Route as AuthTenantsTenantIdFuelIndexRouteImport } from './routes/_auth/tenants/$tenantId/fuel/index'
import { Route as AuthTenantsTenantIdVehiclesCreateRouteImport } from './routes/_auth/tenants/$tenantId/vehicles/create'
import { Route as AuthTenantsTenantIdOdometerCreateRouteImport } from './routes/_auth/tenants/$tenantId/odometer/create'
import { Route as AuthTenantsTenantIdOdometerOdometerIdRouteImport } from './routes/_auth/tenants/$tenantId/odometer/$odometerId'
import { Route as AuthTenantsTenantIdFuelCreateRouteImport } from './routes/_auth/tenants/$tenantId/fuel/create'
import { Route as AuthTenantsTenantIdFuelFuelIdRouteImport } from './routes/_auth/tenants/$tenantId/fuel/$fuelId'
import { Route as AuthTenantsTenantIdVehiclesVehicleIdIndexRouteImport } from './routes/_auth/tenants/$tenantId/vehicles/$vehicleId/index'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthTenantsIndexRoute = AuthTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOnboardingMultipleTenantsRoute =
  AuthOnboardingMultipleTenantsRouteImport.update({
    id: '/onboarding/multiple-tenants',
    path: '/onboarding/multiple-tenants',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOnboardingInvitationRoute =
  AuthOnboardingInvitationRouteImport.update({
    id: '/onboarding/invitation',
    path: '/onboarding/invitation',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthOnboardingCreateTenantRoute =
  AuthOnboardingCreateTenantRouteImport.update({
    id: '/onboarding/create-tenant',
    path: '/onboarding/create-tenant',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdIndexRoute =
  AuthTenantsTenantIdIndexRouteImport.update({
    id: '/tenants/$tenantId/',
    path: '/tenants/$tenantId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdVehiclesIndexRoute =
  AuthTenantsTenantIdVehiclesIndexRouteImport.update({
    id: '/tenants/$tenantId/vehicles/',
    path: '/tenants/$tenantId/vehicles/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdOperationIndexRoute =
  AuthTenantsTenantIdOperationIndexRouteImport.update({
    id: '/tenants/$tenantId/operation/',
    path: '/tenants/$tenantId/operation/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdOdometerIndexRoute =
  AuthTenantsTenantIdOdometerIndexRouteImport.update({
    id: '/tenants/$tenantId/odometer/',
    path: '/tenants/$tenantId/odometer/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdFuelIndexRoute =
  AuthTenantsTenantIdFuelIndexRouteImport.update({
    id: '/tenants/$tenantId/fuel/',
    path: '/tenants/$tenantId/fuel/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdVehiclesCreateRoute =
  AuthTenantsTenantIdVehiclesCreateRouteImport.update({
    id: '/tenants/$tenantId/vehicles/create',
    path: '/tenants/$tenantId/vehicles/create',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdOdometerCreateRoute =
  AuthTenantsTenantIdOdometerCreateRouteImport.update({
    id: '/tenants/$tenantId/odometer/create',
    path: '/tenants/$tenantId/odometer/create',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdOdometerOdometerIdRoute =
  AuthTenantsTenantIdOdometerOdometerIdRouteImport.update({
    id: '/tenants/$tenantId/odometer/$odometerId',
    path: '/tenants/$tenantId/odometer/$odometerId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdFuelCreateRoute =
  AuthTenantsTenantIdFuelCreateRouteImport.update({
    id: '/tenants/$tenantId/fuel/create',
    path: '/tenants/$tenantId/fuel/create',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdFuelFuelIdRoute =
  AuthTenantsTenantIdFuelFuelIdRouteImport.update({
    id: '/tenants/$tenantId/fuel/$fuelId',
    path: '/tenants/$tenantId/fuel/$fuelId',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthTenantsTenantIdVehiclesVehicleIdIndexRoute =
  AuthTenantsTenantIdVehiclesVehicleIdIndexRouteImport.update({
    id: '/tenants/$tenantId/vehicles/$vehicleId/',
    path: '/tenants/$tenantId/vehicles/$vehicleId/',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/': typeof AuthIndexRoute
  '/onboarding/create-tenant': typeof AuthOnboardingCreateTenantRoute
  '/onboarding/invitation': typeof AuthOnboardingInvitationRoute
  '/onboarding/multiple-tenants': typeof AuthOnboardingMultipleTenantsRoute
  '/tenants': typeof AuthTenantsIndexRoute
  '/tenants/$tenantId': typeof AuthTenantsTenantIdIndexRoute
  '/tenants/$tenantId/fuel/$fuelId': typeof AuthTenantsTenantIdFuelFuelIdRoute
  '/tenants/$tenantId/fuel/create': typeof AuthTenantsTenantIdFuelCreateRoute
  '/tenants/$tenantId/odometer/$odometerId': typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  '/tenants/$tenantId/odometer/create': typeof AuthTenantsTenantIdOdometerCreateRoute
  '/tenants/$tenantId/vehicles/create': typeof AuthTenantsTenantIdVehiclesCreateRoute
  '/tenants/$tenantId/fuel': typeof AuthTenantsTenantIdFuelIndexRoute
  '/tenants/$tenantId/odometer': typeof AuthTenantsTenantIdOdometerIndexRoute
  '/tenants/$tenantId/operation': typeof AuthTenantsTenantIdOperationIndexRoute
  '/tenants/$tenantId/vehicles': typeof AuthTenantsTenantIdVehiclesIndexRoute
  '/tenants/$tenantId/vehicles/$vehicleId': typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/': typeof AuthIndexRoute
  '/onboarding/create-tenant': typeof AuthOnboardingCreateTenantRoute
  '/onboarding/invitation': typeof AuthOnboardingInvitationRoute
  '/onboarding/multiple-tenants': typeof AuthOnboardingMultipleTenantsRoute
  '/tenants': typeof AuthTenantsIndexRoute
  '/tenants/$tenantId': typeof AuthTenantsTenantIdIndexRoute
  '/tenants/$tenantId/fuel/$fuelId': typeof AuthTenantsTenantIdFuelFuelIdRoute
  '/tenants/$tenantId/fuel/create': typeof AuthTenantsTenantIdFuelCreateRoute
  '/tenants/$tenantId/odometer/$odometerId': typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  '/tenants/$tenantId/odometer/create': typeof AuthTenantsTenantIdOdometerCreateRoute
  '/tenants/$tenantId/vehicles/create': typeof AuthTenantsTenantIdVehiclesCreateRoute
  '/tenants/$tenantId/fuel': typeof AuthTenantsTenantIdFuelIndexRoute
  '/tenants/$tenantId/odometer': typeof AuthTenantsTenantIdOdometerIndexRoute
  '/tenants/$tenantId/operation': typeof AuthTenantsTenantIdOperationIndexRoute
  '/tenants/$tenantId/vehicles': typeof AuthTenantsTenantIdVehiclesIndexRoute
  '/tenants/$tenantId/vehicles/$vehicleId': typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/onboarding/create-tenant': typeof AuthOnboardingCreateTenantRoute
  '/_auth/onboarding/invitation': typeof AuthOnboardingInvitationRoute
  '/_auth/onboarding/multiple-tenants': typeof AuthOnboardingMultipleTenantsRoute
  '/_auth/tenants/': typeof AuthTenantsIndexRoute
  '/_auth/tenants/$tenantId/': typeof AuthTenantsTenantIdIndexRoute
  '/_auth/tenants/$tenantId/fuel/$fuelId': typeof AuthTenantsTenantIdFuelFuelIdRoute
  '/_auth/tenants/$tenantId/fuel/create': typeof AuthTenantsTenantIdFuelCreateRoute
  '/_auth/tenants/$tenantId/odometer/$odometerId': typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  '/_auth/tenants/$tenantId/odometer/create': typeof AuthTenantsTenantIdOdometerCreateRoute
  '/_auth/tenants/$tenantId/vehicles/create': typeof AuthTenantsTenantIdVehiclesCreateRoute
  '/_auth/tenants/$tenantId/fuel/': typeof AuthTenantsTenantIdFuelIndexRoute
  '/_auth/tenants/$tenantId/odometer/': typeof AuthTenantsTenantIdOdometerIndexRoute
  '/_auth/tenants/$tenantId/operation/': typeof AuthTenantsTenantIdOperationIndexRoute
  '/_auth/tenants/$tenantId/vehicles/': typeof AuthTenantsTenantIdVehiclesIndexRoute
  '/_auth/tenants/$tenantId/vehicles/$vehicleId/': typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/'
    | '/onboarding/create-tenant'
    | '/onboarding/invitation'
    | '/onboarding/multiple-tenants'
    | '/tenants'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/fuel/$fuelId'
    | '/tenants/$tenantId/fuel/create'
    | '/tenants/$tenantId/odometer/$odometerId'
    | '/tenants/$tenantId/odometer/create'
    | '/tenants/$tenantId/vehicles/create'
    | '/tenants/$tenantId/fuel'
    | '/tenants/$tenantId/odometer'
    | '/tenants/$tenantId/operation'
    | '/tenants/$tenantId/vehicles'
    | '/tenants/$tenantId/vehicles/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/onboarding/create-tenant'
    | '/onboarding/invitation'
    | '/onboarding/multiple-tenants'
    | '/tenants'
    | '/tenants/$tenantId'
    | '/tenants/$tenantId/fuel/$fuelId'
    | '/tenants/$tenantId/fuel/create'
    | '/tenants/$tenantId/odometer/$odometerId'
    | '/tenants/$tenantId/odometer/create'
    | '/tenants/$tenantId/vehicles/create'
    | '/tenants/$tenantId/fuel'
    | '/tenants/$tenantId/odometer'
    | '/tenants/$tenantId/operation'
    | '/tenants/$tenantId/vehicles'
    | '/tenants/$tenantId/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_guest/login'
    | '/_guest/register'
    | '/_auth/'
    | '/_auth/onboarding/create-tenant'
    | '/_auth/onboarding/invitation'
    | '/_auth/onboarding/multiple-tenants'
    | '/_auth/tenants/'
    | '/_auth/tenants/$tenantId/'
    | '/_auth/tenants/$tenantId/fuel/$fuelId'
    | '/_auth/tenants/$tenantId/fuel/create'
    | '/_auth/tenants/$tenantId/odometer/$odometerId'
    | '/_auth/tenants/$tenantId/odometer/create'
    | '/_auth/tenants/$tenantId/vehicles/create'
    | '/_auth/tenants/$tenantId/fuel/'
    | '/_auth/tenants/$tenantId/odometer/'
    | '/_auth/tenants/$tenantId/operation/'
    | '/_auth/tenants/$tenantId/vehicles/'
    | '/_auth/tenants/$tenantId/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/tenants/': {
      id: '/_auth/tenants/'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthTenantsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/multiple-tenants': {
      id: '/_auth/onboarding/multiple-tenants'
      path: '/onboarding/multiple-tenants'
      fullPath: '/onboarding/multiple-tenants'
      preLoaderRoute: typeof AuthOnboardingMultipleTenantsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/invitation': {
      id: '/_auth/onboarding/invitation'
      path: '/onboarding/invitation'
      fullPath: '/onboarding/invitation'
      preLoaderRoute: typeof AuthOnboardingInvitationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/onboarding/create-tenant': {
      id: '/_auth/onboarding/create-tenant'
      path: '/onboarding/create-tenant'
      fullPath: '/onboarding/create-tenant'
      preLoaderRoute: typeof AuthOnboardingCreateTenantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/': {
      id: '/_auth/tenants/$tenantId/'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthTenantsTenantIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/vehicles/': {
      id: '/_auth/tenants/$tenantId/vehicles/'
      path: '/tenants/$tenantId/vehicles'
      fullPath: '/tenants/$tenantId/vehicles'
      preLoaderRoute: typeof AuthTenantsTenantIdVehiclesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/operation/': {
      id: '/_auth/tenants/$tenantId/operation/'
      path: '/tenants/$tenantId/operation'
      fullPath: '/tenants/$tenantId/operation'
      preLoaderRoute: typeof AuthTenantsTenantIdOperationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/odometer/': {
      id: '/_auth/tenants/$tenantId/odometer/'
      path: '/tenants/$tenantId/odometer'
      fullPath: '/tenants/$tenantId/odometer'
      preLoaderRoute: typeof AuthTenantsTenantIdOdometerIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/fuel/': {
      id: '/_auth/tenants/$tenantId/fuel/'
      path: '/tenants/$tenantId/fuel'
      fullPath: '/tenants/$tenantId/fuel'
      preLoaderRoute: typeof AuthTenantsTenantIdFuelIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/vehicles/create': {
      id: '/_auth/tenants/$tenantId/vehicles/create'
      path: '/tenants/$tenantId/vehicles/create'
      fullPath: '/tenants/$tenantId/vehicles/create'
      preLoaderRoute: typeof AuthTenantsTenantIdVehiclesCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/odometer/create': {
      id: '/_auth/tenants/$tenantId/odometer/create'
      path: '/tenants/$tenantId/odometer/create'
      fullPath: '/tenants/$tenantId/odometer/create'
      preLoaderRoute: typeof AuthTenantsTenantIdOdometerCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/odometer/$odometerId': {
      id: '/_auth/tenants/$tenantId/odometer/$odometerId'
      path: '/tenants/$tenantId/odometer/$odometerId'
      fullPath: '/tenants/$tenantId/odometer/$odometerId'
      preLoaderRoute: typeof AuthTenantsTenantIdOdometerOdometerIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/fuel/create': {
      id: '/_auth/tenants/$tenantId/fuel/create'
      path: '/tenants/$tenantId/fuel/create'
      fullPath: '/tenants/$tenantId/fuel/create'
      preLoaderRoute: typeof AuthTenantsTenantIdFuelCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/fuel/$fuelId': {
      id: '/_auth/tenants/$tenantId/fuel/$fuelId'
      path: '/tenants/$tenantId/fuel/$fuelId'
      fullPath: '/tenants/$tenantId/fuel/$fuelId'
      preLoaderRoute: typeof AuthTenantsTenantIdFuelFuelIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tenants/$tenantId/vehicles/$vehicleId/': {
      id: '/_auth/tenants/$tenantId/vehicles/$vehicleId/'
      path: '/tenants/$tenantId/vehicles/$vehicleId'
      fullPath: '/tenants/$tenantId/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthOnboardingCreateTenantRoute: typeof AuthOnboardingCreateTenantRoute
  AuthOnboardingInvitationRoute: typeof AuthOnboardingInvitationRoute
  AuthOnboardingMultipleTenantsRoute: typeof AuthOnboardingMultipleTenantsRoute
  AuthTenantsIndexRoute: typeof AuthTenantsIndexRoute
  AuthTenantsTenantIdIndexRoute: typeof AuthTenantsTenantIdIndexRoute
  AuthTenantsTenantIdFuelFuelIdRoute: typeof AuthTenantsTenantIdFuelFuelIdRoute
  AuthTenantsTenantIdFuelCreateRoute: typeof AuthTenantsTenantIdFuelCreateRoute
  AuthTenantsTenantIdOdometerOdometerIdRoute: typeof AuthTenantsTenantIdOdometerOdometerIdRoute
  AuthTenantsTenantIdOdometerCreateRoute: typeof AuthTenantsTenantIdOdometerCreateRoute
  AuthTenantsTenantIdVehiclesCreateRoute: typeof AuthTenantsTenantIdVehiclesCreateRoute
  AuthTenantsTenantIdFuelIndexRoute: typeof AuthTenantsTenantIdFuelIndexRoute
  AuthTenantsTenantIdOdometerIndexRoute: typeof AuthTenantsTenantIdOdometerIndexRoute
  AuthTenantsTenantIdOperationIndexRoute: typeof AuthTenantsTenantIdOperationIndexRoute
  AuthTenantsTenantIdVehiclesIndexRoute: typeof AuthTenantsTenantIdVehiclesIndexRoute
  AuthTenantsTenantIdVehiclesVehicleIdIndexRoute: typeof AuthTenantsTenantIdVehiclesVehicleIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthOnboardingCreateTenantRoute: AuthOnboardingCreateTenantRoute,
  AuthOnboardingInvitationRoute: AuthOnboardingInvitationRoute,
  AuthOnboardingMultipleTenantsRoute: AuthOnboardingMultipleTenantsRoute,
  AuthTenantsIndexRoute: AuthTenantsIndexRoute,
  AuthTenantsTenantIdIndexRoute: AuthTenantsTenantIdIndexRoute,
  AuthTenantsTenantIdFuelFuelIdRoute: AuthTenantsTenantIdFuelFuelIdRoute,
  AuthTenantsTenantIdFuelCreateRoute: AuthTenantsTenantIdFuelCreateRoute,
  AuthTenantsTenantIdOdometerOdometerIdRoute:
    AuthTenantsTenantIdOdometerOdometerIdRoute,
  AuthTenantsTenantIdOdometerCreateRoute:
    AuthTenantsTenantIdOdometerCreateRoute,
  AuthTenantsTenantIdVehiclesCreateRoute:
    AuthTenantsTenantIdVehiclesCreateRoute,
  AuthTenantsTenantIdFuelIndexRoute: AuthTenantsTenantIdFuelIndexRoute,
  AuthTenantsTenantIdOdometerIndexRoute: AuthTenantsTenantIdOdometerIndexRoute,
  AuthTenantsTenantIdOperationIndexRoute:
    AuthTenantsTenantIdOperationIndexRoute,
  AuthTenantsTenantIdVehiclesIndexRoute: AuthTenantsTenantIdVehiclesIndexRoute,
  AuthTenantsTenantIdVehiclesVehicleIdIndexRoute:
    AuthTenantsTenantIdVehiclesVehicleIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
